//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Db.Linq2dbImplementation.DataModels
{
	/// <summary>
	/// Database       : test_linq2db
	/// Data Source    : tcp://localhost:5432
	/// Server Version : 9.5.2
	/// </summary>
	public partial class TestContext : LinqToDB.Data.DataConnection
	{
		public ITable<entity_a>           entity_a           { get { return this.GetTable<entity_a>(); } }
		public ITable<entity_b>           entity_b           { get { return this.GetTable<entity_b>(); } }
		public ITable<some_data_entity_a> some_data_entity_a { get { return this.GetTable<some_data_entity_a>(); } }
		public ITable<some_data_entity_b> some_data_entity_b { get { return this.GetTable<some_data_entity_b>(); } }
		public ITable<some_object>        some_object        { get { return this.GetTable<some_object>(); } }

		public TestContext()
			: base("Postgres")
		{
			InitDataContext();
		}

		public TestContext(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table(Schema="public", Name="entity_a")]
	public partial class entity_a
	{
		[PrimaryKey, NotNull] public Guid   id      { get; set; } // uuid
		[Column,     NotNull] public string prop_a1 { get; set; } // character varying
		[Column,     NotNull] public bool   prop_a2 { get; set; } // boolean

		#region Associations

		/// <summary>
		/// some_data_entity_a_entity_id_fkey_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="entity_id", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<some_data_entity_a> somedataentityaentityidfkeys { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="entity_b")]
	public partial class entity_b
	{
		[PrimaryKey, NotNull] public Guid    id      { get; set; } // uuid
		[Column,     NotNull] public decimal prop_b1 { get; set; } // numeric(4,2)
		[Column,     NotNull] public decimal prop_b2 { get; set; } // numeric(4,2)

		#region Associations

		/// <summary>
		/// some_data_entity_b_entity_id_fkey_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="entity_id", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<some_data_entity_b> somedataentitybentityidfkeys { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="some_data_entity_a")]
	public partial class some_data_entity_a
	{
        /*
		[PrimaryKey, Identity] public int            id                    { get; set; } // integer
		[Column,     NotNull ] public Guid           entity_id             { get; set; } // uuid
		[Column,     NotNull ] public Guid           linked_object_id      { get; set; } // uuid
		[Column,     NotNull ] public DateTimeOffset last_access_timestamp { get; set; } // timestamp (6) with time zone
		[Column,     NotNull ] public EntityType     entity_type           { get; set; } // smallint
        */
		#region Associations

		/// <summary>
		/// some_data_entity_a_entity_id_fkey
		/// </summary>
		[Association(ThisKey="entity_id", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="some_data_entity_a_entity_id_fkey", BackReferenceName="somedataentityaentityidfkeys")]
		public entity_a somedataentityaentityidfkey { get; set; }

		/// <summary>
		/// some_data_entity_a_linked_object_id_fkey
		/// </summary>
		[Association(ThisKey="linked_object_id", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="some_data_entity_a_linked_object_id_fkey", BackReferenceName="somedataentityalinkedobjectidfkeys")]
		public some_object somedataentityalinkedobjectidfkey { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="some_data_entity_b")]
	public partial class some_data_entity_b
	{
        /*
		[PrimaryKey, Identity] public int            id                    { get; set; } // integer
		[Column,     NotNull ] public Guid           entity_id             { get; set; } // uuid
		[Column,     NotNull ] public Guid           linked_object_id      { get; set; } // uuid
		[Column,     NotNull ] public DateTimeOffset last_access_timestamp { get; set; } // timestamp (6) with time zone
		[Column,     NotNull ] public EntityType     entity_type           { get; set; } // smallint
        */
		#region Associations

		/// <summary>
		/// some_data_entity_b_entity_id_fkey
		/// </summary>
		[Association(ThisKey="entity_id", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="some_data_entity_b_entity_id_fkey", BackReferenceName="somedataentitybentityidfkeys")]
		public entity_b somedataentitybentityidfkey { get; set; }

		/// <summary>
		/// some_data_entity_b_linked_object_id_fkey
		/// </summary>
		[Association(ThisKey="linked_object_id", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="some_data_entity_b_linked_object_id_fkey", BackReferenceName="somedataentityblinkedobjectidfkeys")]
		public some_object somedataentityblinkedobjectidfkey { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="some_object")]
	public partial class some_object
	{
		[PrimaryKey, NotNull] public Guid id { get; set; } // uuid

		#region Associations

		/// <summary>
		/// some_data_entity_a_linked_object_id_fkey_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="linked_object_id", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<some_data_entity_a> somedataentityalinkedobjectidfkeys { get; set; }

		/// <summary>
		/// some_data_entity_b_linked_object_id_fkey_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="linked_object_id", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<some_data_entity_b> somedataentityblinkedobjectidfkeys { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static entity_a Find(this ITable<entity_a> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static entity_b Find(this ITable<entity_b> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static some_data_entity_a Find(this ITable<some_data_entity_a> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static some_data_entity_b Find(this ITable<some_data_entity_b> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static some_object Find(this ITable<some_object> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}
	}
}
